# Generated by Django 5.1.2 on 2024-10-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_product_date_created_product_date_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducr',
            new_name='OrderProduct',
        ),
    ]
