# Generated by Django 5.1.2 on 2024-10-20 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de creacion'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de actualizacion'),
        ),
    ]
