# Generated by Django 5.1.2 on 2024-10-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_create_date_product_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_date',
        ),
    ]
